version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes: 
       - ./blank-theme:/var/www/html/wp-content/themes/blank-theme
       - ./blank-plugin:/var/www/html/wp-content/plugins/blank-plugin
       - ./uploads:/var/www/html/wp-content/uploads     
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     depends_on: 
      - db
     restart: always
     ports:
      - "8080:80"
     environment:
      - PMA_ARBITRARY=1   
       
       
volumes:
    db_data: